

<div class="main-container">
    <div class="page-position">
        <h2>لوحة التحكم</h2>
        <p>/</p>
        <h6>المعاملات</h6>
    </div>
    <div class="container payments">
        <div class="search-container">
            <h3>البحث المتقدم</h3>
            <div class="search-box">
                <input type="text" placeholder="اسم المستخدم">
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">الباقة</option>
                        <option value="">مصر</option>
                        <option value="">السعودية</option>
                    </select>
                    <span></span>
                </div>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">وسيلة الدفع</option>
                        <option value="">مصر</option>
                        <option value="">السعودية</option>
                    </select>
                    <span></span>
                </div>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">الاجراء المتخذ</option>
                        <option value="">مصر</option>
                        <option value="">السعودية</option>
                    </select>
                    <span></span>
                </div>
            </div>
        </div>
        <div class="table-container">
            <div class="table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم المستخدم</th>
                            <th>الباقة</th>
                            <th>تاريخ المعاملة</th>
                            <th>وسيلة الدفع</th>
                            <th>الإجراء</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->payments as $payment):?>
                        <tr>
                            <td><?=$payment->id?></td>
                            <td><?=$payment->user?></td>
                            <td><?=$payment->package?></td>
                            <td><?=$payment->create_date?></td>
                            <td><?=$payment->method?></td>
                            <td class="action">
                                <?php if(empty($payment->status)):?>
                                    <form method="POST">
                                        <input type="hidden" name="id" value="<?=$payment->id?>">
                                        <input type="hidden" name="user_id" value="<?=$payment->user_id?>">
                                        <button class="btn-confirm" name="confirm">تأكيد</button>
                                    </form>
                                    <form method="POST">
                                        <input type="hidden" name="id" value="<?=$payment->id?>">
                                        <input type="hidden" name="user_id" value="<?=$payment->user_id?>">
                                        <button class="btn-unvalid" name="unvalid">غير صالحة</button>
                                    </form>
                                <?php else:?>
                                    <?=$payment->status?>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="pagination">

            </div>
        </div>
    </div>
</div>
