

<!--The footer holds the link to my webiste ELAHMAWY DEV , All rights of design is setntenced to ELASHMAWY DEV-->
<footer>
   <div>
       designed by <a href="https://elashmawydev.com" style="color: #1dd1a1;cursor: pointer;">ELASHMAWY DEV</a>
   </div> 
</footer>


<script src="<?php echo PUBLIC_URL;?>assets/js/ajax.js"></script>
<script src="<?php echo PUBLIC_URL;?>assets/js/main.js"></script>

</body>
</html>