
<div class="main-container">
    <div class="page-position">
        <h2>لوحة التحكم</h2>
        <p>/</p>
        <h6>الأعضاء</h6>
    </div>
    <div class="container users">
        <div class="search-container">
            <h3>البحث المتقدم</h3>
            <div class="search-box">
                <input type="text" placeholder="اسم المستخدم">
                <input type="text" placeholder="البريد الالكتروني">
                <input type="text" placeholder="الاسم">
                <input type="text" placeholder="رقم الهاتف">
                <input type="text" placeholder="#">
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">الجنس</option>
                        <option value="">ذكر</option>
                        <option value="">أنثي</option>
                    </select>
                    <span></span>
                </div>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">الدولة</option>
                        <option value="">مصر</option>
                        <option value="">السعودية</option>
                    </select>
                    <span></span>
                </div>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="">المنطقة</option>
                        <option value="">مصر</option>
                        <option value="">السعودية</option>
                    </select>
                    <span></span>
                </div>
                
            </div>
        </div>

        <div class="table-container">
            <div class="table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم المستخدم</th>
                            <th>الحالة</th>
                            <th>العضوية</th>
                            <th>انتهاء العضوية</th>
                            <th>البريد الالكتروني</th>
                            <th>الاسم</th>
                            <th>الجنس</th>
                            <th>الدولة</th>
                            <th>المنطقة</th>
                            <th>رقم الهاتف</th>
                            <th>الإجراء</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->users as $user): ?>
                        <tr>
                            <td><?=$user->id?></td>
                            <td><?=$user->username?></td>
                            <td><?=$user->status?></td>
                            <td><?=$user->account_type_txt?></td>
                            <td><?=$user->special_account_deadline?></td>
                            <td><?=$user->email?></td>
                            <td><?=$user->full_name?></td>
                            <td><?=$user->gender?></td>
                            <td><?=$user->country?></td>
                            <td><?=$user->state?></td>
                            <td><?=$user->phone_number?></td>
                            <td class="action"><button data-user-id="<?=$user->id?>" class="btn-edit" onclick="get_user_info(this);">جميع البيانات</button>
                            <img data-user-id="<?=$user->id?>" data-ban="<?=$user->ban?>" data-account-type="<?=$user->account_type?>" src="<?php echo PUBLIC_URL;?>assets/img/pencil.svg" alt="تعديل" title="تعديل البيانات" onclick="get_user_edit(this);"></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="pagination">

            </div>
        </div>
    </div>
</div>





<!--edit user Box BEGIN-->
<div class="float-box-container">

    <div class="edit-user-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->

        <h3>المستخدم رقم #<span class="user_id"></span></h3>
        <div class="input-items">

            <!--Deactivate User-->
            <form method="POST" name="deactivate_user">
                <input type="hidden" name="id">
                <div class="input-item"><button class="deactivate-btn" name="deactivate_user" type="submit">تعطيل الحساب</button></div>
            </form>

            <!--Activate User-->
            <form method="POST" name="activate_user">
                <input type="hidden" name="id">
                <div class="input-item"><button class="activate-btn" name="activate_user" type="submit">تفعيل الحساب</button></div>
            </form>


            <!--Delete User-->
            <form method="POST" name="delete_user">
                <input type="hidden" name="id">
                <div class="input-item"><button class="delete-btn" name="delete_user" type="submit">حذف الحساب نهائيا</button></div>
            </form>

        </div>
        <div class="input-items" id="upgrade-forms">
            <!--Upgrade User #1 month-->
            <form method="POST">
                <input type="hidden" name="id">
                <input type="hidden" name="plan" value="1">
                <div class="input-item"><button class="upgrade-btn" name="upgrade_special" type="submit">ترقية لمدة شهر</button></div>
            </form>

            <!--Upgrade User #3 month-->
            <form method="POST">
                <input type="hidden" name="id">
                <input type="hidden" name="plan" value="3">
                <div class="input-item"><button class="upgrade-btn" name="upgrade_special" type="submit">ترقية لمدة ثلاثة أشهر</button></div>
            </form>

            <!--Upgrade User #1 year-->
            <form method="POST">
                <input type="hidden" name="id">
                <input type="hidden" name="plan" value="12">
                <div class="input-item"><button class="upgrade-btn" name="upgrade_special" type="submit">ترقية لمدة عام</button></div>
            </form>
        </div>

        <div class="input-items" id="disupgrade-form">
            <!--Disupgrade User-->
            <form method="POST">
                <input type="hidden" name="id">
                <div class="input-item"><button class="disupgrade-btn" name="disupgrade" type="submit">تحويل الي عضوية عادية</button></div>
            </form>
        </div>
    </div>
</div>
<!--edit user Box END-->



<!--show user Box BEGIN-->
<div class="float-box-container">

    <div class="show-user-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <input type="hidden" name="id">
        <h3>بيانات المستخدم رقم #<span class="user_id"></span></h3>
        <table class="show-user-table">
           
        </table>
    </div>
</div>
<!--show user Box END-->


<script>
    function get_user_edit(el){
        id = el.getAttribute('data-user-id');
        var edit_user_box = document.querySelector('.edit-user-box');
        edit_user_box.querySelector('span.user_id').innerHTML = id;
        edit_user_box.querySelectorAll('input[name="id"]').forEach(input => {
            input.setAttribute('value', id);
        });
        
        //ban
        if(el.getAttribute('data-ban') == 0) {
            hide(document.forms['activate_user']);
            show(document.forms['deactivate_user']);
        } else {
            hide(document.forms['deactivate_user']);
            show(document.forms['activate_user']);
        }
        
        if(el.getAttribute('data-account-type') == 1) {
            show(edit_user_box.querySelector('#disupgrade-form'));
            hide(edit_user_box.querySelector('#upgrade-forms'));
        } else {
            hide(edit_user_box.querySelector('#disupgrade-form'));
            show(edit_user_box.querySelector('#upgrade-forms'));
        }

        popupBox('.edit-user-box');
    }
</script>