
<div class="main-container">
    <div class="page-position">
        <h2>لوحة التحكم</h2>
        <p>/</p>
        <h6>الإحصائيات</h6>
    </div>
    <div class="container">
        <div class="stats">
            <div class="head">
                <h3>كل الوقت</h3>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="اليوم">اليوم</option>
                        <option value="الأمس">الأمس</option>
                        <option value="أول أمس">أول أمس</option>
                    </select>
                    <span></span>
                </div>
            </div>
            <div class="boxs">
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
            </div>
            <span class="line"></span>
        </div>
        <div class="stats">
            <div class="head">
                <h3>كل الوقت</h3>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="اليوم">اليوم</option>
                        <option value="الأمس">الأمس</option>
                        <option value="أول أمس">أول أمس</option>
                    </select>
                    <span></span>
                </div>
            </div>
            <div class="boxs">
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
            </div>
            <span class="line"></span>
        </div>
        <div class="stats">
            <div class="head">
                <h3>كل الوقت</h3>
                <div class="select-item">
                    <select name="" id="" onclick="rotateSelect(this)">
                        <option value="اليوم">اليوم</option>
                        <option value="الأمس">الأمس</option>
                        <option value="أول أمس">أول أمس</option>
                    </select>
                    <span></span>
                </div>
            </div>
            <div class="boxs">
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
                <div class="stats-box">
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                    <span></span>
                    <div class="item">
                        <div class="num">125</div>
                        <div class="title">الرجال</div>
                    </div>
                </div>
            </div>         
            <span class="line"></span>   
        </div>
    </div>

</div>
